# Secret holds Account microservice confidential data
apiVersion: v1 # K8S API version
kind: Secret
metadata:
  name: account-service-secret
  namespace: cba-dev # The name of the namespace
  labels:
    app: account-service
    tier: backend
    environment: development
type: Opaque
stringData:
  database-user: cba
  database-password: pa$$wOrd123!
  secret-key: HVxWhjNes0vU3FyxETpmBcYXyV0WVAgw
