# ConfigMap holds information about Account microservice configuration files
apiVersion: v1 # K8S API version
kind: ConfigMap
metadata:
  name: account-service-configmap
  namespace: cba-dev # The name of the namespace
  labels:
    app: account-service
    tier: backend
    environment: development
data:
  APP_SETTINGS: development
  NAME: Account REST API Service
  VERSION: 1.0.0
  API_VERSION: v1
  FORCE_HTTPS: False
  DATABASE_USER: cba
  DATABASE_NAME: account_db
  DATABASE_HOST: localhost
  DATABASE_PORT: 15432
  PROMETHEUS_HOSTNAME: prometheus
  PROMETHEUS_PORT: 19090
  SWAGGER_ENABLED: True
