# PersistentVolumeClaim is a request for storage for pipeline.
apiVersion: v1 # K8S API version
kind: PersistentVolumeClaim
metadata:
  name: cba-pipeline-pvc # Name of the PVC
  labels:
    app: cba-pipeline
    environment: development
    team: devops
spec:
  accessModes:
    - ReadWriteMany # Allow multiple nodes to read/write from/to the volume simultaneously
  resources:
    requests:
      storage: 1Gi # Request 1GiB of storage space
  volumeMode: Filesystem # The volume mode set to 'Filesystem' for mounting the volume as a file system
  storageClassName: gp3 # You can get available storage classes with oc get storageclass
