# Secret holds CBA pipeline confidential data
apiVersion: v1 # K8S API version
kind: Secret
metadata:
  name: cba-pipeline-secret # Name of the secret
  labels:
    app: cba-pipeline
    environment: development
    team: devops
type: Opaque
stringData:
  token: 453574vU3FyxETpmBcYX....
  database_uri: postgresql://postgres:pa$$wOrd123!@postgres:5432/account_db
